# Site
repository: AstraBert/my-resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Clelia Astra Bertelli
title: Open Source Engineer @ LlamaIndex
email: astraberte9@gmail.com
# email_title: Email (Email title override)
phone:
# phone_title: Phone (Phone title override)
website: https://clelia.dev
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: itsclelia
github_username: AstraBert
linkedin_username: clelia-astra-bertelli-583904297
orcid_username: 0009-0002-3595-0498

# Additional icon links
additional_links:
  - title: All my social media
    icon: fas fa-link
    url: https://link.clelia.dev
  - title: My Blog
    icon: far fa-pen
    url: https://clelia.dev/blog/

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/me.jpeg
about_content: |
  I'm Clelia, a software engineer with a passion for open source and AI, coding in languages like Python, Go, Rust and Typescript/Javascript.

  I am goal-driven, ambitious, and always on the look for the next challenge.

  Building is my passion: I love creating useful automation in my day-to-day life, as well as I dive more than happily into weekend projects!

  I also love writing, tackling both technical and scientific topics for the sake of open science (I had my BSc. in Biology!)

content:
  - title: My Top Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: # Value of `weak` will display a weak border below this item. # Any
          # other value (or no value) means no border will be displayed
        title: PdfItDown
        link: https://github.com/AstraBert/PdfItDown
        link_text: GitHub Repository
        quote: >
          Convert (almost) any file to PDF!
        description: | # this will include new lines to allow paragraphs
          PdfItDown is a python package and CLI tool to convert most file formats into PDF for GenAI application!
      - layout: left
        border: # Value of `weak` will display a weak border below this item. # Any
          # other value (or no value) means no border will be displayed
        title: workflows-acp
        link: https://github.com/AstraBert/workflows-acp
        link_text: GitHub Repository
        quote: >
          Generalist Agent built on LlamaIndex Workflows and Agent Client Protocol.
        description: | # this will include new lines to allow paragraphs
          workflows-acp is a python package and CLI application that can connect to any ACP client and perform complex tasks with built-in support for MCPs, filesystem and bash tools, memory, TODO tracking and sandboxing via AgentFS. It supports all major models by Anthropic, OpenAI and Google
      - layout: left
        border: # Value of `weak` will display a weak border below this item. # Any
          # other value (or no value) means no border will be displayed
        title: jake
        link: https://jake-build.com
        link_text: Website
        quote: >
          A Rust-based Make alternative for Unix operating systems.
        description: | # this will include new lines to allow paragraphs
          jake is a task executor written in Rust, with simplicity and feature-richness at the core: TOML-based task definition, dependency resolution, support for loading env vars, dry-runs, listing tasks, initializing boilerplate files, executing scripts from package.json...
      - layout: left
        border: # Value of `weak` will display a weak border below this item. # Any
          # other value (or no value) means no border will be displayed
        title: squite
        link: https://squite.de
        link_text: Website
        quote: >
          A UI for SQLite, written in Rust.
        description: | # this will include new lines to allow paragraphs
          SqUIte is a Desktop app that serves as a UI for SQLite, built with egui and rusqulite.
      - layout: left
        border: # Value of `weak` will display a weak border below this item. # Any
          # other value (or no value) means no border will be displayed
        title: agentfs-claude
        link: https://github.com/run-llama/agentfs-claude
        link_text: GitHub Repository
        quote: >
          Run Claude Code/Codex within AgentFS, orchestrated by LlamaIndex Workflows
        description: | # this will include new lines to allow paragraphs
          agentfs-claude is a CLI tool that allows you to run Claude Code and Codex on a virtual filesystem (AgentFS) instead of your real one, preventing damages deriving from deletions or modifications.
      - layout: left
        border: # Value of `weak` will display a weak border below this item. # Any
          # other value (or no value) means no border will be displayed
        title: what-a-git-year
        link: https://gityear.re
        link_text: Website
        quote: >
          Spotify Wrapped for GitHub.
        description: | # this will include new lines to allow paragraphs
          A full-stack application built with Go, allowing users and organizations to get statistics about their profile on GitHub. It features several system design concepts such as authentication/authorization, rate limiting, CORS, caching and monitoring.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: LlamaIndex
        sub_title: Open Source Engineer
        caption: May 2025 - present
        link: https://llamaindex.ai
        quote: >
          Automating document workflows with AI
        description: | # this will include new lines to allow paragraphs
          I am one of the maintainers of LlamaIndex OSS framework, both for Python and Typescript. I also contribute to other LlamaIndex-managed projects, such as [Semtools](https://github.com/run-llama/semtools) (Rust-based CLI for local document intelligence), and build projects and demos related to our open-source and cloud products.
      - layout: left
        title: LegalForLandlords
        sub_title: AI Engineer
        caption: February 2025 - May 2025
        link: https://lfl.co.uk
        quote: >
          Automating legal documents understanding with AI
        description: | # this will include new lines to allow paragraphs
          I contributed to build a pipeline for processing legal documents using AI agents orchestration.
      - layout: left
        title: Natural History Museum Vienna
        sub_title: Bioinformatics Researcher
        caption: October 2024 - March 2025
        link: https://www.nhm.at
        quote: >
          Insect genomics and biostatistics.
        description: | # this will include new lines to allow paragraphs
          In my six-months fellowship, I researched human-driven impact on the genetic differentiation of fruit flies in Europe using quantitative genome data.
      - layout: left
        title: Criad Ltd
        sub_title: Founding Engineer
        caption: June 2024 - February 2025
        link:
        quote: >
          Building the next space for designers and architects, using AI
        description: | # this will include new lines to allow paragraphs
          I was involved in the first phases of development and iteration over a product that would represent a new, AI-powered space for A&D.

  - title: Education
    layout: list
    content:
      - layout: top-left
        title: University of Pavia
        sub_title: BSc. Biological Sciences
        caption: 2022-2025
        quote: >
          Biological Sciences program with a focus on Genetics and Bioinformatics
        description: | # this will include new lines to allow paragraphs
          As a Biology undergraduate student, I followed courses about Genetics, Physiology, Evolution, Ecology and (Bio)chemistry. My focus has been, throughout my Bachelor's degree, mostly on Bioinformatics.
          My dissertation was titled: ["Exploring Potential Commensality Patterns between Drosophila melanogaster and Homo sapiens in Europe"](https://docs.google.com/presentation/d/11WHJccFQ-YBKR5tBoHDoDOZ3eiPvGDacoaLCyT6wW5I/edit?usp=sharing) and was supervised by doct. Lino Ometto (University of Pavia) and doct. Martin Kapun (NHM Vienna).
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      My skills, beyond being a python developer, AI (agentic workflows, coding agents, developer tooling, MCP...), encompass DevOps (especially with Docker), git and GitHub, Go and Rust... I am trying my best to build many diversified projects in my free time to upskill as much as I can.

      I am a passionate person: I try to do my best whenever I can. I value solo work, but I discovered that I value work more when it is a team effort, and many people contribute to iterate and build something wonderful!

      Beyond my technical skills, indeed, I spent a lot of time focusing on building good soft skills, such as speaking in public and pitching ideas or story-telling them through reports or presentations, as well as cultivating transparent communication.

      My interests, beyond programming, are travel, art (and museums!), my cat and sports (although I generally prefer the gym).

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
